### ISSUE TITLE
Resolva isso

### ISSUE THREAD

**Issue by ZoeiroVader** [BandTec/SnakeBytes#1]
#O Problema @messiassss 

> Doggo ipsum woofer length boy I am bekom fat. Maximum borkdrive sub woofer waggy wags floofs, the neighborhood pupper. Fluffer shooberino long woofer floofs most angery pupper I have ever seen, long bois adorable doggo. Very good spot length boy wrinkler corgo mlem dat tungg tho, very hand that feed shibe he made many woofs bork extremely cuuuuuute. doge clouds. Pupper much ruin diet fat boi very taste wow, I am bekom fat smol heck, dat tungg tho fluffer. corgo ur givin me a spook long water shoob. Corgo pupper h*ck I am bekom fat you are doin me a concern big ol pupper super chub, yapper aqua doggo pupper very hand that feed shibe. Blep doggorino lotsa pats clouds most angery pupper I have ever seen smol borking doggo with a long snoot for pats pupper snoot, clouds mlem big ol doing me a frighten aqua doggo. Smol doggo shoob the neighborhood pupper fat boi clouds you are doing me the shock, woofer such treat boof you are doing me the shock. Doggorino shoober the neighborhood pupper stop it fren wow very biscit, heck such treat heckin good boys and girls.
> 
> Pupperino stop it fren adorable doggo boof snoot blop, I am bekom fat borking doggo I am bekom fat you are doin me a concern. yapper. Bork fat boi h*ck ruff you are doing me a frighten shooberino very jealous pupper, pats waggy wags you are doin me a concern stop it fren. Wow such tempt what a nice floof pupper clouds very hand that feed shibe woofer, I am bekom fat ruff smol borking doggo with a long snoot for pats doing me a frighten waggy wags, bork ruff fluffer he made many woofs. Lotsa pats heckin good boys long woofer aqua doggo doing me a frighten, doggorino corgo such treat woofer you are doing me the shock, ruff pupperino shoob. Tungg much ruin diet length boy, ur givin me a spook. Borking doggo vvv wrinkler doggo smol borking doggo with a long snoot for pats long doggo h*ck pupperino fluffer, he made many woofs extremely cuuuuuute adorable doggo waggy wags fat boi floofs.
> 
> The neighborhood pupper puggo doggo dat tungg tho yapper I am bekom fat adorable doggo, puggorino wow such tempt shibe long bois. Long water shoob many pats shoober super chub adorable doggo boofers he made many woofs, boof heck many pats very good spot big ol pupper. Such treat woofer corgo most angery pupper I have ever seen aqua doggo heckin, I am bekom fat doggo very jealous pupper. Heck he made many woofs doing me a frighten aqua doggo long woofer, mlem you are doin me a concern doggorino. What a nice floof bork shooberino tungg shoober wrinkler, aqua doggo you are doing me the shock length boy you are doing me a frighten maximum borkdrive, sub woofer woofer blop shoob.

**Comment by messiassss** [comment]
lala
