### ISSUE TITLE
Modifique Isso

### ISSUE THREAD

**Issue by ZoeiroVader** [BandTec/SnakeBytes#4]
#A Modificação @GabrielBiussi 

> #orem ipsum dolor sit amet, consectetur adipiscing elit. In sapien augue, tempor nec dignissim vel, varius at tellus. Fusce non massa non sem feugiat condimentum in in magna. Nam a felis ut arcu accumsan tempor gravida ut diam. Donec molestie cursus lorem, in lacinia urna consequat a. Curabitur rhoncus quis lectus nec aliquet. In risus ante, suscipit et ligula sed, commodo consectetur mi. Aenean vestibulum porta risus et molestie. Maecenas nec lectus ornare, posuere risus varius, imperdiet libero. Quisque non posuere felis, quis viverra magna. Curabitur varius tortor quis nibh consequat fringilla. Curabitur vel molestie dui. Morbi dolor risus, gravida sit amet metus in, sollicitudin dapibus enim. Nam non sagittis dolor, non tempor tellus. Sed ac blandit diam, euismod dignissim nisi.

**Comment by GabrielBiussi** [comment]
resolvido
